name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage;Format=lcov"

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: /home/runner/work/Jaco/Jaco/JacoTests/TestResults/
